name: Dev Box Create Repo Test

on:
  workflow_dispatch:

jobs:
  run-devbox:
    runs-on: ubuntu-latest

    steps:
      - name: Create repo via GitHub API
        run: |
          curl -X POST https://api.github.com/user/repos \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d '{
            "name": "devbox-test-repo",
            "private": true
          }'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
